name: remote-sensing-fusion

channels:
  - conda-forge
  - defaults

dependencies:
  # Core dependencies
  - python=3.7

  # Core scientific python
  - matplotlib
  - numpy
  - seaborn

  # Spatial packages
  - rasterio
  - geopandas
  - earthpy

  # Jupyter Environment
  - autopep8
  - jupyterlab
  - notebook
  - ipython
  - jupyter_contrib_nbextensions
  - nbclean
